steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=.env.enc
  - --plaintext-file=.env
  - --location=global
  - --keyring=docker-snippets
  - --key=docker-snippets-env
  id: DECRYPT
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/npm'
  args: ['install', '--only=prod']
  id: ROOT_INSTALL
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/npm'
  dir: 'client'
  args: ['install']
  id: CLIENT_INSTALL
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run','test:client']
  id: CLIENT_TEST
  waitFor:
    - CLIENT_INSTALL

- name: 'gcr.io/cloud-builders/npm'
  args: ['run','build:client']
  id: CLIENT_BUILD
  waitFor:
    - CLIENT_TEST
    - DECRYPT

- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy', '--only', 'hosting']
  waitFor:
    - ROOT_INSTALL
    - CLIENT_BUILD
    - DECRYPT