steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=.env.enc
  - --plaintext-file=.env
  - --location=global
  - --keyring=docker-snippets
  - --key=docker-snippets-env
  id: DECRYPT
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/npm'
  args: ['install',]
  id: ROOT_INSTALL
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/npm'
  dir: 'client'
  args: ['install']
  id: CLIENT_INSTALL
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/npm'
  dir: 'client'
  args: ['run','test:unit']
  id: CLIENT_TEST
  waitFor:
    - CLIENT_INSTALL

- name: 'gcr.io/cloud-builders/npm'
  dir: 'client'
  args: ['run','build', '--prod']
  id: CLIENT_BUILD
  waitFor:
    - CLIENT_TEST
    - DECRYPT

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'deploy']
  waitFor:
    - ROOT_INSTALL
    - CLIENT_BUILD
    - DECRYPT