steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  dir: 'client'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  dir: 'client'
  args: ['run','test:unit']

- name: 'gcr.io/cloud-builders/npm'
  dir: 'client'
  args: ['run','build', '--prod']

- name: 'gcr.io/cloud-builders/npm'
  dir: 'functions'
  args: ['install']

- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy']