steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=.env.enc
  - --plaintext-file=.env
  - --location=global
  - --keyring=docker-snippets
  - --key=docker-snippets-env

- name: 'gcr.io/cloud-builders/npm'
  dir: 'client'
  args: ['install']
  id: CLIENT_INSTALL
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/npm'
  dir: 'client'
  args: ['run','test:unit']
  id: CLIENT_TEST
  waitFor:
    - CLIENT_INSTALL

- name: 'gcr.io/cloud-builders/npm'
  dir: 'client'
  args: ['run','build', '--prod']
  id: CLIENT_BUILD
  waitFor:
    - CLIENT_TEST

- name: 'gcr.io/cloud-builders/npm'
  dir: 'admin-site'
  args: ['install']
  id: ADMIN_INSTALL
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/npm'
  dir: 'admin-site'
  id: ADMIN_BUILD
  args: ['run','build', '--prod']
  waitFor:
    - ADMIN_INSTALL

- name: 'gcr.io/cloud-builders/npm'
  dir: 'functions'
  args: ['install']
  id: FUNCTIONS_INSTALL
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'deploy']
  waitFor:
    - FUNCTIONS_INSTALL
    - ADMIN_BUILD
    - CLIENT_BUILD